name: Flutter CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  run-flutter-tests:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v3

      - name: 2. Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable" # Use the 'stable' version of Flutter

      - name: 3. Install dependencies
        run: flutter pub get

      # Process fail ho rha hai step 4 par, trying to remove unit tests...

      - name: 5. Run integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          script: flutter test integration_test
