name: Flutter CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  run-flutter-tests:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v3

      - name: 2. Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: 3. Install dependencies
        run: flutter pub get

      - name: 4. Verify devices (optional)
        run: flutter devices

      - name: 5. Run integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel_4
          emulator-options: -no-window -no-audio -no-boot-anim -gpu swiftshader_indirect -accel off
          script: |
            adb wait-for-device
            adb shell getprop sys.boot_completed
            flutter test integration_test
