name: Flutter CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  run-flutter-tests:
    runs-on: macos-latest

    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v3

      - name: 2. Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: 3. Install dependencies
        run: flutter pub get

      - name: 4. Create google-services.json
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" > android/app/google-services.json

      - name: 5. Run integration tests on Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          profile: pixel_6
          script: |
            flutter test integration_test/app_test.dart
