name: Flutter CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  run-flutter-tests:
    runs-on: macos-latest

    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v3

      - name: 2. Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: 3. Install dependencies
        run: flutter pub get

      - name: 4. Run integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: default
          arch: x86_64
          script: flutter test -d emulator-5554 integration_test/app_test.dart
